export { default as plusIcon } from "./menu/plusIcon.svg";
export { default as friendsIcon } from "./menu/friendsIcon.svg";
export { default as profileIcon } from "./menu/profileIcon.svg";
export { default as closeIcon } from "./closeIcon.svg";
export { default as discoBacll } from "./discoBall.svg";
export { default as login } from "./login.svg";
export { default as testProfile } from "./testProfile.png";
export { default as cam } from "./Room/cam.svg";
export { default as mic} from "./Room/mic.svg";
export { default as noneRedCam} from "./Room/noneCamRed.svg";
export { default as noneWhiteCam} from "./Room/noneCamWhite.svg";
export { default as noneRedMic} from "./Room/noneMicRed.svg";